CREATE TABLE IF NOT EXISTS dm.personal_data (
key integer PRIMARY KEY generated by default as identity
, id int, name text, surname text, email text, 
frc text, position text, ranking integer);

CREATE TABLE IF NOT EXISTS dm.employee_skill (
id integer PRIMARY KEY generated by default as identity
, employee_id int, skill_type text, skill_name text, 
grade_name text, sort integer);

